name: "En_GBLocalise in translations"

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  engb-localise:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check PR content
      id: build
      run: |
          cd ./joomla_v4/translations/package
          mkdir ./logs
          grep -rn --include \*.php 'En_GBLocalise' > ./logs/En_GBLocalise_result.txt
          cat ./logs/En_GBLocalise_result.txt
    - name: Check existence of En_GBLocalise_result.txt file
      id: check_result_file
      uses: andstor/file-existence-action@v1
      with:
        files: ./joomla_v4/translations/package/logs/En_GBLocalise_result.txt

    - name: Save PR number
      if: ${{ always() }}
      run: echo ${{ github.event.pull_request.number }} > ./joomla_v4/translations/package/logs/PR_number.txt
      
    - name: Save PR sha
      if: ${{ always() }}
      run: echo ${{ github.sha }} > ./joomla_v4/translations/package/logs/PR_sha.txt

    - name: Prepare issue commebt
      run: |
          echo "The following translation files contain the En_GBLocalise class on ${{ github.sha }}" >> ./joomla_v4/translations/package/logs/En_GBLocalise_comment.md
          echo "```" >> ./joomla_v4/translations/package/logs/En_GBLocalise_comment.md
          cat ./joomla_v4/translations/package/logs/En_GBLocalise_result.txt >> ./joomla_v4/translations/package/logs/En_GBLocalise_comment.md
          echo "```" >> ./joomla_v4/translations/package/logs/En_GBLocalise_comment.md

    - name: fail workflow
      if: steps.check_result_file.outputs.files_exists == 'true'
      run: exit 1

    - name: Upload En_GBLocalise-logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: En_GBLocalise-logs
        path: ./joomla_v4/translations/package/logs
