name: Check existens of En_GBLocalise in translations

on:
  pull_request_target:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  engb-localise:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Check PR content
      id: build
      run: |
          cd ./joomla_v4/translations/package
          grep -rn --include \*.php 'En_GBLocalise' > ./list.txt
          echo "build-log<<EOF" >> $GITHUB_ENV
          echo -e "$(cat list.txt)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          cat list.txt
    - name: Check existence of list.txt file
      id: check_list_file
      uses: andstor/file-existence-action@v1
      with:
        files: ./joomla_v4/translations/package/list.txt
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: 'The following translation files contain the En_GBLocalise'
    - uses: peter-evans/create-or-update-comment@v2
      name: Add PR comment
      if: ${{ github.event.pull_request.number != '' && steps.check_list_file.outputs.files_exists == 'true' && steps.fc.outputs.comment-id == '' }}
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
             The following translation files contain the En_GBLocalise class on ${{ github.sha }}
             ```
             ${{ env.build-log }}
             ```
    - name: Update comment
      if: ${{ github.event.pull_request.number != '' && steps.check_list_file.outputs.files_exists == 'true' && steps.fc.outputs.comment-id != '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.check_list_file.outputs.files_exists == 'true' && steps.fc.outputs.comment-id }}
        body: |
             The following translation files contain the En_GBLocalise class on ${{ github.sha }}
             ```
             ${{ env.build-log }}
              ```
        edit-mode: replace
    - name: fail workflow
      if: steps.check_list_file.outputs.files_exists == 'true'
      run: exit 1
 
